/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 water_splash_spiral.glb 
Author: Will VFX (https://sketchfab.com/wjcvfilm)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/water-splash-spiral-282e1a5d84f5472281e72f35987775e7
Title: Water Splash Spiral
*/
import React from 'react'
import { useGLTF } from '@react-three/drei'

export function Water(props) {
  const { nodes, materials } = useGLTF('/models/water_splash_spiral.glb')
  return (
    <group {...props} dispose={null}>
      <group scale={0.01}>
        <mesh geometry={nodes.Liquid__0.geometry} material={materials['Scene_-_Root']} />
        <mesh geometry={nodes.Liquid__0_1.geometry} material={materials['Scene_-_Root']} />
        <mesh geometry={nodes.Liquid__0_2.geometry} material={materials['Scene_-_Root']} />
        <mesh geometry={nodes.Liquid__0_3.geometry} material={materials['Scene_-_Root']} />
        <mesh geometry={nodes.Liquid__0_4.geometry} material={materials['Scene_-_Root']} />
      </group>
    </group>
  )
}

useGLTF.preload('/models/water_splash_spiral.glb')
