/* eslint-disable */
import * as Router from 'expo-router';

export * from 'expo-router';

declare module 'expo-router' {
  export namespace ExpoRouter {
    export interface __routes<T extends string | object = string> {
      hrefInputParams: { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `${'/(barber-tabs)'}` | `/`; params?: Router.UnknownInputParams; } | { pathname: `${'/(barber-tabs)'}/profile` | `/profile`; params?: Router.UnknownInputParams; } | { pathname: `${'/(barber-tabs)'}/shop` | `/shop`; params?: Router.UnknownInputParams; } | { pathname: `${'/(customer-tabs)'}/bookings` | `/bookings`; params?: Router.UnknownInputParams; } | { pathname: `${'/(customer-tabs)'}` | `/`; params?: Router.UnknownInputParams; } | { pathname: `${'/(customer-tabs)'}/profile` | `/profile`; params?: Router.UnknownInputParams; } | { pathname: `/auth`; params?: Router.UnknownInputParams; } | { pathname: `/customer-tabs/booking-detail`; params?: Router.UnknownInputParams; } | { pathname: `/+not-found`, params: Router.UnknownInputParams & {  } };
      hrefOutputParams: { pathname: Router.RelativePathString, params?: Router.UnknownOutputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownOutputParams } | { pathname: `/`; params?: Router.UnknownOutputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(barber-tabs)'}` | `/`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(barber-tabs)'}/profile` | `/profile`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(barber-tabs)'}/shop` | `/shop`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(customer-tabs)'}/bookings` | `/bookings`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(customer-tabs)'}` | `/`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(customer-tabs)'}/profile` | `/profile`; params?: Router.UnknownOutputParams; } | { pathname: `/auth`; params?: Router.UnknownOutputParams; } | { pathname: `/customer-tabs/booking-detail`; params?: Router.UnknownOutputParams; } | { pathname: `/+not-found`, params: Router.UnknownOutputParams & {  } };
      href: Router.RelativePathString | Router.ExternalPathString | `/${`?${string}` | `#${string}` | ''}` | `/_sitemap${`?${string}` | `#${string}` | ''}` | `${'/(barber-tabs)'}${`?${string}` | `#${string}` | ''}` | `/${`?${string}` | `#${string}` | ''}` | `${'/(barber-tabs)'}/profile${`?${string}` | `#${string}` | ''}` | `/profile${`?${string}` | `#${string}` | ''}` | `${'/(barber-tabs)'}/shop${`?${string}` | `#${string}` | ''}` | `/shop${`?${string}` | `#${string}` | ''}` | `${'/(customer-tabs)'}/bookings${`?${string}` | `#${string}` | ''}` | `/bookings${`?${string}` | `#${string}` | ''}` | `${'/(customer-tabs)'}${`?${string}` | `#${string}` | ''}` | `/${`?${string}` | `#${string}` | ''}` | `${'/(customer-tabs)'}/profile${`?${string}` | `#${string}` | ''}` | `/profile${`?${string}` | `#${string}` | ''}` | `/auth${`?${string}` | `#${string}` | ''}` | `/customer-tabs/booking-detail${`?${string}` | `#${string}` | ''}` | { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `${'/(barber-tabs)'}` | `/`; params?: Router.UnknownInputParams; } | { pathname: `${'/(barber-tabs)'}/profile` | `/profile`; params?: Router.UnknownInputParams; } | { pathname: `${'/(barber-tabs)'}/shop` | `/shop`; params?: Router.UnknownInputParams; } | { pathname: `${'/(customer-tabs)'}/bookings` | `/bookings`; params?: Router.UnknownInputParams; } | { pathname: `${'/(customer-tabs)'}` | `/`; params?: Router.UnknownInputParams; } | { pathname: `${'/(customer-tabs)'}/profile` | `/profile`; params?: Router.UnknownInputParams; } | { pathname: `/auth`; params?: Router.UnknownInputParams; } | { pathname: `/customer-tabs/booking-detail`; params?: Router.UnknownInputParams; } | `/+not-found` | { pathname: `/+not-found`, params: Router.UnknownInputParams & {  } };
    }
  }
}
